### ISSUE TITLE
Add workshop to golang Learning Tutorials section of ReposHub

### ISSUE THREAD

**Issue by leecalcote** [layer5io/advanced-istio-service-mesh-workshop#25]
**Current Behavior**
ReposHub has a section for golang  Learning Tutorials: https://reposhub.com/go/Learning-Tutorial

**Desired Behavior**
Contact ReposHub to have this repo added to the Learning Tutorials category.

**Comment by sayantan1413** [comment]
Yes @leecalcote closing this issue as I couldn't find the solution here.
