### ISSUE TITLE
to fix error in "Slack Notify on Star" Job under GitHub Actions 

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/advanced-istio-service-mesh-workshop#29]
## Description
Under **GitHub Actions** of this repository **"[Slack Notify on Star](https://github.com/layer5io/advanced-istio-service-mesh-workshop/actions/runs/6325366964)"** job is failing for which [Slack.yaml](https://github.com/layer5io/advanced-istio-service-mesh-workshop/blob/master/.github/workflows/slack.yml) is to be Updated.

## Fix
To fix this issue, update the code of [slack.yaml](https://github.com/layer5io/advanced-istio-service-mesh-workshop/blob/master/.github/workflows/slack.yml) just by copy/pasting the code from[ slack.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/slack.yml) of [meshery](https://github.com/meshery/meshery)

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.

**Comment by rj2704** [comment]
I can fix these issues. Could you please assign it to me?

**Comment by saurabh100ni** [comment]
Hey @rj2704, as @akhilender-bongirwar requested first so on fair basis I'll be assigning it to @akhilender-bongirwar.
Ps: there are other so many open issue you may wanna work on 👀

**Comment by DeeptanshuDas** [comment]
can I work on this issue
