### ISSUE TITLE
Add GitHub action to notify Slack on star of repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/advanced-istio-service-mesh-workshop#7]
**Description:**
When someone stars this repo, it is encouraging to the community of contributors when a notification is received in the community slack workspace.

**Implementation:**
Using this [slack.yaml](https://github.com/layer5io/service-mesh-performance/blob/master/.github/workflows/slack.yml) (GitHub Action) as an example to copy directly from, create a `.github/workflows` folders, copy and modify the slack.yaml file to suite this repo.

**Comment by bojanderson** [comment]
I can take a crack at this! Looks pretty straightforward

**Comment by PluckyPrecious** [comment]
Sure @bojanderson go ahead.👍🏽

**Comment by PluckyPrecious** [comment]
Hi @gaurav7019 bojanderson is on it, I could hook you up with another if you don’t mind.👍🏽

**Comment by bojanderson** [comment]
@leecalcote this was already working before you even created this issue.

I joined the Slack channel, checked the Buzz channel and starred this repo and then saw this notification.

The ```.github/workflows/slack.yaml``` file already exists too. So I think you can close this issue, no PR needed. But if you have any other repos that need this set up, let me know.

![image](https://user-images.githubusercontent.com/26066615/95932958-2e21ef80-0d9b-11eb-9b53-76f30f94acc4.png)

**Comment by leecalcote** [comment]
@bojanderson oh, that's too funny. Thanks for digging in here.

Yes, this repo could be uplifting with the same workflow - https://github.com/layer5io/homebrew-tap. That would be nice.

**Comment by leecalcote** [comment]
Thanks for looking into this issue as well, @gaurav7019 👍

**Comment by bojanderson** [comment]
@leecalcote that one has it too. I think it's been added to the template that you're forking from

**Comment by leecalcote** [comment]
Ah, geez. Clearly, I'm trying to do too many things at once. You're right - it is there under the .github/workflows folder. And, yes, many of the `layer5io` repos are created from a common repo template. The original `slack.yaml` in that template needs an initial update to be repo-specific, but beyond that, the slack.yaml's are good to go.

If GitHub Action workflows are an area of interest, you might fancy helping fully establish the "edge" release channel for many of the Meshery adapters. The [Meshery Build & Release Strategy document](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit) should be updated outlines the approach to the creation of stable and edge channels, if it's of interest.
